### ISSUE TITLE
After install

### ISSUE THREAD

**Issue by Jelly9912** [ImagicalCorp/PocketMine-MP-Releases#1]
After install i see in menu red light and version 0.11. Can i still join on 0.13 ??

**Comment by thebigsmileXD** [comment]
Not sure if i compiled it right.. i launched 0.11 and compiled the source folder. @keithkfng Please have a look ok?

**Comment by keithkfng** [comment]
I compiled the "pocketmine", "spl", and "raklib" folders, because I thought the src folder was only on GitHub and wasn't needed when compiling PocketMine sources. Anyway, which phar are you using @Jelly9912?

**Comment by Jelly9912** [comment]
Still 0.11 lol

**Comment by keithkfng** [comment]
Can you join the actual server?

**Comment by Jelly9912** [comment]
No, i can't '~'
